version: "2.1"

services:
  s3:
    hostname: s3
    image: minio/minio:RELEASE.2018-05-04T23-13-12Z
    environment:
      MINIO_ACCESS_KEY: foobar
      MINIO_SECRET_KEY: foobarfoo
    ports:
      - 9000:9000
    volumes:
      - ./docker/s3/data:/data
      - ./docker/s3/config:/root/.minio
    command: server /data
    networks:
      - infra

  simulator-java:
    hostname: simulator-java
    image: dsc:simulator-local
    user: jenkins
    mem_limit: 6072m
    entrypoint: ["/bin/bash", "-e" ,"run_java_job.sh"]
    environment:
      JBEHAVE_STORY: GenerateTestFiles
      ENVIRONMENT: sit
      OFFER_COUNT: 2
      OFFER_ALLOCATION_PER_MEMBER: 1
      FF_USER_COUNT: 90
      DATE_GENERATED: "2019-05-16"
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobarfoo
      ENDPOINT_URL: "--endpoint-url http://s3:9000/"
    volumes:
      - ${HOME}/.m2:${HOME}/.m2
    networks:
      - infra

  simulator-python:
    hostname: simulator-python
    image: dsc:simulator-local
    user: jenkins
    mem_limit: 6072m
    entrypoint: ["/bin/bash", "-e" ,"run_python_job.sh"]
    environment:
      ENVIRONMENT: sit
      DATE_GENERATED: "2019-05-16"
      EXECUTE_RUNNER: "ConvertCsvToParquet.py"
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobarfoo
      ENDPOINT_URL: "--endpoint-url http://s3:9000/"
    networks:
      - infra

networks:
  infra:
    external:
      name: dsc_local_infra
